drop table INSTRUMENT_DBF;
CREATE TABLE INSTRUMENT_DBF (INSTRUMENT VARCHAR(4), DATE integer, LOW FLOAT, ME FLOAT, HIGH FLOAT, MED FLOAT, VOL INTEGER);

LOAD DATA LOCAL INFILE '/home/yoann/Fullstack/Datastore/INSTRUMENT.txt' INTO TABLE INSTRUMENT_DBF FIELDS TERMINATED BY ',';


	
 -- ALTER TABLE INSTRUMENT_DBF
-- ADD COLUMN DATE VARCHAR(8) AFTER INSTRMENT;


-- ALTER TABLE INSTRUMENT_DBF MODIFY COLUMN INSTRMENT VARCHAR(4);

-- ALTER TABLE INSTRUMENT_DBF CHANGE COLUMN INSTRMENT INSTRUMENT VARCHAR(4);
-- ALTER TABLE INSTRUMENT_DBF CHANGE COLUMN INSTRMENT to INSTRUMENT;

-- ALTER TABLE INSTRUMENT_DBF RENAME COLUMN "INSTRMENT" TO "INSTRUMENT" VARCHAR(4);
